export const constants = {
    success: 1,
    alert: 2,
    error: 3,
    confirm: 4,
    errorTitle: 'Error!',
    deleteTitle: 'Eliminar registro',
    solicitudTitle: 'Enviar solicitud',
    successTitle: 'Confirmación',
    successCreate: "Se creó exitosamente!",
    successRecuperar: "Hemos enviado su nueva contraseña a su correo electrónico",
    successCambio: "La contraseña se cambió exitosamente",
    successLogin: "Ingreso exitoso, bienvenido!",
    successDelete: "Se eliminó exitosamente!",
    successUpdate: "Se actualizó exitosamente!",
    alreadyExist: "Ya existe",
    enUso: "Entidad en uso",
    errorCreate: "Error al tratar de crear el registro!",
    errorRecuperar: "Error al tratar de restablecer la nueva contraseña!",
    errorCambio: "No se pudo cambiar la contraseña actual!",
    errorDelete: "Error al tratar de eliminar el registro!",
    errorUpdate: "Error al tratar de actualizar el registro!",
    errorLogin: "Error al tratar de ingresar al sistema!",
    errorUnautorized: "Por favor verifique sus credenciales!",
    errorAlreadyExists: "Este registro ya existe",
    errorEnUso: "No se puede eliminar este registro porque ya está siendo usado!",
    userAlreadyExists: "Este usuario ya se encuentra registrado en el sistema, por favor verifique su correo y su número de documento...",
    confirmDelete: "¿Está seguro que desea eliminar este registro?",
    confirmSolicitud: "¿Enviar solicitud para pujar en esta subasta?",
    confirmDeleteEvento: "¿Está seguro que desea eliminar este evento, también se eliminarán los elementos asociados como subastas, lotes y animales...?",
    confirmDeleteSubasta: "¿Está seguro que desea eliminar esta subasta, también se eliminarán los elementos asociados como lotes y animales...?"
}