// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Subasta.repository;

namespace Subasta.Migrations
{
    [DbContext(typeof(SubastaContext))]
    [Migration("20190216154215_actualizo_campos_bd")]
    partial class actualizo_campos_bd
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Subasta.repository.models.Animal", b =>
                {
                    b.Property<int>("AnimalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("CODIGO_ANI");

                    b.Property<bool>("Activo")
                        .HasColumnName("ACTIVO_ANI");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnName("DESCRIPCION_ANI")
                        .HasMaxLength(2000);

                    b.Property<string>("Foto")
                        .IsRequired()
                        .HasColumnName("FOTO_ANI")
                        .HasMaxLength(200);

                    b.Property<int>("LoteId")
                        .HasColumnName("COD_LOTE_ANI");

                    b.Property<int>("MunicipioId")
                        .HasColumnName("COD_MUN_PROCE_ANI");

                    b.Property<decimal>("Peso")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("PESO_ANI")
                        .HasDefaultValue(0m);

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasColumnName("SEXO_ANI");

                    b.HasKey("AnimalId");

                    b.HasIndex("LoteId");

                    b.HasIndex("MunicipioId");

                    b.ToTable("TBL_ANIMALES");
                });

            modelBuilder.Entity("Subasta.repository.models.Categoria", b =>
                {
                    b.Property<int>("CategoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("CODIGO_CAT");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnName("NOMBRE_CAT")
                        .HasMaxLength(50);

                    b.HasKey("CategoriaId");

                    b.ToTable("TBL_CATEGORIAS");
                });

            modelBuilder.Entity("Subasta.repository.models.Clasificacion", b =>
                {
                    b.Property<int>("ClasificacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("CODIGO_CLAS");

                    b.Property<int>("CategoriaId");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnName("NOMBRE_CLAS")
                        .HasMaxLength(50);

                    b.HasKey("ClasificacionId");

                    b.HasIndex("CategoriaId");

                    b.ToTable("TBL_CLASIFICACIONES");
                });

            modelBuilder.Entity("Subasta.repository.models.Cliente", b =>
                {
                    b.Property<string>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID_CLI")
                        .HasMaxLength(15);

                    b.Property<bool>("Activo")
                        .HasColumnName("ACTIVO_CLI");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnName("CORREO_CLI")
                        .HasMaxLength(50);

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnName("DIRECCION_CLI")
                        .HasMaxLength(50);

                    b.Property<int>("MunicipioId")
                        .HasColumnName("CODIGO_MUN_CLI");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnName("NOMBRE_CLI")
                        .HasMaxLength(70);

                    b.Property<string>("Representante")
                        .HasColumnName("REPRESENTANTE_LEGAL_CLI")
                        .HasMaxLength(70);

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnName("TELEFONO_CLI")
                        .HasMaxLength(20);

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnName("TIPO_CLI")
                        .HasMaxLength(20);

                    b.Property<int>("TipoDocumentoId")
                        .HasColumnName("CODIGO_TD_CLI");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasColumnName("USUARIO_CLI")
                        .HasMaxLength(50);

                    b.HasKey("ClienteId");

                    b.HasIndex("MunicipioId");

                    b.HasIndex("TipoDocumentoId");

                    b.ToTable("TBL_CLIENTES");
                });

            modelBuilder.Entity("Subasta.repository.models.Departamento", b =>
                {
                    b.Property<int>("DepartamentoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("CODIGO_DPTO");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnName("NOMBRE_DPTO")
                        .HasMaxLength(50);

                    b.HasKey("DepartamentoId");

                    b.ToTable("TBL_DEPARTAMENTOS");
                });

            modelBuilder.Entity("Subasta.repository.models.Evento", b =>
                {
                    b.Property<int>("EventoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("CODIGO_EVEN");

                    b.Property<bool>("Activo")
                        .HasColumnName("ACTIVO_EVEN");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnName("NOMBRE_EVEN")
                        .HasMaxLength(50);

                    b.Property<DateTime>("FechaFin")
                        .HasColumnName("FECHA_FIN_EVEN");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnName("FECHA_INI_EVEN");

                    b.Property<int>("MunicipioId")
                        .HasColumnName("UBICACION_EVEN");

                    b.HasKey("EventoId");

                    b.HasIndex("MunicipioId");

                    b.ToTable("TBL_EVENTOS");
                });

            modelBuilder.Entity("Subasta.repository.models.Lote", b =>
                {
                    b.Property<int>("LoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("CODIGO_LOTE");

                    b.Property<bool>("Activo")
                        .HasColumnName("ACTIVO_LOTE");

                    b.Property<int>("CantidadElementos")
                        .HasColumnName("CANTIDAD_ELEMENTOS_LOTE");

                    b.Property<int>("CategoriaId")
                        .HasColumnName("COD_CATEGORIA_LOTE");

                    b.Property<int>("ClasificacionId")
                        .HasColumnName("COD_CLASIFICACION_LOTE");

                    b.Property<string>("ClienteId")
                        .IsRequired()
                        .HasColumnName("ID_CLIENTE_LOTE");

                    b.Property<string>("Descripcion")
                        .HasColumnName("DESCRIPCION_LOTE")
                        .HasMaxLength(2000);

                    b.Property<string>("FotoLote")
                        .IsRequired()
                        .HasColumnName("FOTO_LOTE")
                        .HasMaxLength(200);

                    b.Property<int>("MunicipioId")
                        .HasColumnName("COD_MUN_UBI_LOTE");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnName("NOMBRE_LOTE")
                        .HasMaxLength(50);

                    b.Property<decimal>("PesoPromedio")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("PESO_PROMEDIO_LOTE")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("PesoTotal")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("PESO_TOTAL_LOTE")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("PrecioBase")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("PRECIO_BASE_LOTE")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("PrecioInicial")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("PRECIO_INICIAL_LOTE")
                        .HasDefaultValue(0m);

                    b.Property<int>("RazaId")
                        .HasColumnName("COD_RAZA_LOTE");

                    b.Property<int>("SubastaId")
                        .HasColumnName("COD_SUBASTA_LOTE");

                    b.HasKey("LoteId");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("ClasificacionId");

                    b.HasIndex("ClienteId");

                    b.HasIndex("MunicipioId");

                    b.HasIndex("RazaId");

                    b.HasIndex("SubastaId");

                    b.ToTable("TBL_LOTES");
                });

            modelBuilder.Entity("Subasta.repository.models.Municipio", b =>
                {
                    b.Property<int>("MunicipioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("CODIGO_MUN");

                    b.Property<int>("DepartamentoId")
                        .HasColumnName("COD_DPTO_MUN");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnName("NOMBRE_MUN")
                        .HasMaxLength(50);

                    b.HasKey("MunicipioId");

                    b.HasIndex("DepartamentoId");

                    b.ToTable("TBL_MUNICIPIOS");
                });

            modelBuilder.Entity("Subasta.repository.models.Puja", b =>
                {
                    b.Property<int>("PujaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("CODIGO_PUJA");

                    b.Property<DateTime>("HoraPuja")
                        .HasColumnName("HORA_PUJA");

                    b.Property<int>("PujadorId")
                        .HasColumnName("COD_SUBASTA_PUJADOR");

                    b.Property<decimal>("Valor")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("VALOR_PUJA")
                        .HasDefaultValue(0m);

                    b.HasKey("PujaId");

                    b.HasIndex("PujadorId");

                    b.ToTable("TBL_PUJAS");
                });

            modelBuilder.Entity("Subasta.repository.models.Pujador", b =>
                {
                    b.Property<int>("PujadorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID_PUJADOR");

                    b.Property<string>("Banco")
                        .HasColumnName("BANCO_CONSIGNACION_PUJADOR");

                    b.Property<string>("ClienteId")
                        .IsRequired()
                        .HasColumnName("ID_CLI_PUJADOR");

                    b.Property<string>("Estado")
                        .HasColumnName("ESTADO_PUJADOR");

                    b.Property<int>("LoteId")
                        .HasColumnName("CODIGO_LOTE_PUJADOR");

                    b.Property<string>("NumeroConsignacion")
                        .HasColumnName("NRO_CONSIGNACION_PUJADOR");

                    b.Property<decimal>("ValorConsignacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("VALOR_CONSIGNACION_PUJADOR")
                        .HasDefaultValue(0m);

                    b.HasKey("PujadorId");

                    b.HasIndex("ClienteId");

                    b.HasIndex("LoteId");

                    b.ToTable("TBL_PUJADORES");
                });

            modelBuilder.Entity("Subasta.repository.models.Raza", b =>
                {
                    b.Property<int>("RazaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("CODIGO_RAZA");

                    b.Property<int>("CategoriaId");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnName("NOMBRE_RAZA")
                        .HasMaxLength(50);

                    b.HasKey("RazaId");

                    b.HasIndex("CategoriaId");

                    b.ToTable("TBL_RAZAS");
                });

            modelBuilder.Entity("Subasta.repository.models.Rol", b =>
                {
                    b.Property<int>("RolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("CODIGO_ROL");

                    b.Property<string>("Descripcion")
                        .HasColumnName("DESCRIPCION_ROL")
                        .HasMaxLength(50);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnName("NOMBRE_ROL")
                        .HasMaxLength(50);

                    b.HasKey("RolId");

                    b.ToTable("TBL_ROLES");
                });

            modelBuilder.Entity("Subasta.repository.models.SolicitudSubasta", b =>
                {
                    b.Property<int>("SolicitudId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("CODIGO_SOLI");

                    b.Property<string>("ClienteId")
                        .IsRequired()
                        .HasColumnName("CLIENTE_SOLI");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnName("ESTADO_SOLI")
                        .HasMaxLength(30);

                    b.Property<int>("SubastaId")
                        .HasColumnName("SUBASTA_SOLI");

                    b.HasKey("SolicitudId");

                    b.HasIndex("ClienteId");

                    b.HasIndex("SubastaId");

                    b.ToTable("TBL_SOLICITUDES");
                });

            modelBuilder.Entity("Subasta.repository.models.Subasta", b =>
                {
                    b.Property<int>("SubastaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("CODIGO_SUB");

                    b.Property<bool>("Activo")
                        .HasColumnName("ACTIVO_SUB");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnName("DESCRIPCION_SUB")
                        .HasMaxLength(50);

                    b.Property<int>("EventoId")
                        .HasColumnName("CODIGO_EVENTO_SUB");

                    b.Property<DateTime>("HoraFin")
                        .HasColumnName("FECHA_LIMITE_FIN_SUB");

                    b.Property<DateTime>("HoraInicio")
                        .HasColumnName("FECHA_HORA_INI_SUB");

                    b.Property<decimal>("ValorAnticipo")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("VALOR_ANTICIPO_SUB")
                        .HasDefaultValue(0m);

                    b.HasKey("SubastaId");

                    b.HasIndex("EventoId");

                    b.ToTable("TBL_SUBASTAS");
                });

            modelBuilder.Entity("Subasta.repository.models.TipoDocumento", b =>
                {
                    b.Property<int>("TipoDocumentoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("CODIGO_TD");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnName("NOMBRE_TD")
                        .HasMaxLength(50);

                    b.HasKey("TipoDocumentoId");

                    b.ToTable("TBL_TIPO_DOCUMENTOS");
                });

            modelBuilder.Entity("Subasta.repository.models.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("CODIGO_USU");

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasColumnName("PASS_USUARIO")
                        .HasMaxLength(50);

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnName("CORREO_USUARIO")
                        .HasMaxLength(50);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnName("NOMBRE_USUARIO")
                        .HasMaxLength(50);

                    b.Property<int>("RolId")
                        .HasColumnName("ROL_USUARIO");

                    b.HasKey("UsuarioId");

                    b.HasIndex("RolId");

                    b.ToTable("TBL_USUARIOS");
                });

            modelBuilder.Entity("Subasta.repository.models.Animal", b =>
                {
                    b.HasOne("Subasta.repository.models.Lote", "Lote")
                        .WithMany("Animales")
                        .HasForeignKey("LoteId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Subasta.repository.models.Municipio", "Municipio")
                        .WithMany("Animales")
                        .HasForeignKey("MunicipioId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Subasta.repository.models.Clasificacion", b =>
                {
                    b.HasOne("Subasta.repository.models.Categoria", "Categoria")
                        .WithMany("Clasificaciones")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Subasta.repository.models.Cliente", b =>
                {
                    b.HasOne("Subasta.repository.models.Municipio", "Municipio")
                        .WithMany("Clientes")
                        .HasForeignKey("MunicipioId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Subasta.repository.models.TipoDocumento", "TipoDocumento")
                        .WithMany("Clientes")
                        .HasForeignKey("TipoDocumentoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Subasta.repository.models.Evento", b =>
                {
                    b.HasOne("Subasta.repository.models.Municipio", "Municipio")
                        .WithMany("Eventos")
                        .HasForeignKey("MunicipioId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Subasta.repository.models.Lote", b =>
                {
                    b.HasOne("Subasta.repository.models.Categoria", "Categoria")
                        .WithMany("Lotes")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Subasta.repository.models.Clasificacion", "Clasificacion")
                        .WithMany("Lotes")
                        .HasForeignKey("ClasificacionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Subasta.repository.models.Cliente", "Cliente")
                        .WithMany("Lotes")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Subasta.repository.models.Municipio", "Municipio")
                        .WithMany("Lotes")
                        .HasForeignKey("MunicipioId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Subasta.repository.models.Raza", "Raza")
                        .WithMany("Lotes")
                        .HasForeignKey("RazaId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Subasta.repository.models.Subasta", "Subasta")
                        .WithMany("Lotes")
                        .HasForeignKey("SubastaId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Subasta.repository.models.Municipio", b =>
                {
                    b.HasOne("Subasta.repository.models.Departamento", "Departamento")
                        .WithMany("Municipios")
                        .HasForeignKey("DepartamentoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Subasta.repository.models.Puja", b =>
                {
                    b.HasOne("Subasta.repository.models.Pujador", "Pujador")
                        .WithMany("Pujas")
                        .HasForeignKey("PujadorId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Subasta.repository.models.Pujador", b =>
                {
                    b.HasOne("Subasta.repository.models.Cliente", "Cliente")
                        .WithMany("Pujadores")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Subasta.repository.models.Lote", "Lote")
                        .WithMany("Pujadores")
                        .HasForeignKey("LoteId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Subasta.repository.models.Raza", b =>
                {
                    b.HasOne("Subasta.repository.models.Categoria", "Categoria")
                        .WithMany("Razas")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Subasta.repository.models.SolicitudSubasta", b =>
                {
                    b.HasOne("Subasta.repository.models.Cliente", "Cliente")
                        .WithMany("SolicitudSubastas")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Subasta.repository.models.Subasta", "Subasta")
                        .WithMany("SolicitudSubastas")
                        .HasForeignKey("SubastaId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Subasta.repository.models.Subasta", b =>
                {
                    b.HasOne("Subasta.repository.models.Evento", "Evento")
                        .WithMany("Subastas")
                        .HasForeignKey("EventoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Subasta.repository.models.Usuario", b =>
                {
                    b.HasOne("Subasta.repository.models.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
